### ISSUE TITLE
immediate-value-change not always fired when immediateValue changes

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-slider#136]
https://jsfiddle.net/mgiuffrida/nm1ft4x7/

Why does `immediate-value-change` only fire when the slider is dragged, when `immediateValue` updates whenever the slider is dragged _or_ tapped?

**Comment by danbeam** [comment]
it seems like [part of the doc](https://github.com/PolymerElements/paper-slider/blob/master/paper-slider.html#L407-408) and [the code](https://github.com/PolymerElements/paper-slider/blob/master/paper-slider.html#L510) agree that this should only be fired when dragging, but the [doc on the event itself](https://github.com/PolymerElements/paper-slider/blob/master/paper-slider.html#L741) is agnostic.

it'd be fairly easy to `fire` an `immediate-value-change` from `_bardown` or to always fire events when `this.transiting` instead of just when `this.dragging`.

/cc @keanulee @frankiefu

**Comment by frankiefu** [comment]
The [doc on the event itself](https://github.com/PolymerElements/paper-slider/blob/master/paper-slider.html#L741) needs to be updated so it's clear that `immediate-value-change` only fires when dragging.  Since `immediateValue` is a notified property, you can use `immediate-value-changed` (notice ends with `d`) event to listen for `immediateValue` changes.

**Comment by mgiuffrida** [comment]
thanks guys!
