### ISSUE TITLE
Paper-slider input in editable mode can't be styled with custom properties

### ISSUE THREAD

**Issue by AndreasGalster** [PolymerElements/paper-slider#145]
### Description

It is not possible to style the paper-input with custom properties. I can imagine this is a Polymer issue rather than a paper-slider issue but filing it anyway. It seems the @apply does not support custom properties in a mixin?
### Expected outcome

The input in editable mode changes colors when using custom properties within the mixin.
### Actual outcome

Custom properties are not being changed.
### Steps to reproduce

```
      paper-slider {
        --paper-slider-input: {
          --paper-input-container-color: white;
          --paper-input-container-focus-color: white;
          --paper-input-container-invalid-color: white;
          --paper-input-input-container-input-color: white;
        };
```

**Comment by AndreasGalster** [comment]
Sorry, my bad, it's working as intended.

**Comment by AndreasGalster** [comment]
Nevermind, it really is not working. Interestingly though, **this is working**, which I didn't expected to be the case.

```
      paper-slider {
          paper-input {
            --paper-input-container-color: white;
            --paper-input-container-focus-color: white;
            --paper-input-container-invalid-color: white;
            --paper-input-container-input-color: white;
          }
      }
```

Is this a "it's a bug, not a feature" thing or is this intended behavior with custom properties?

**Comment by notwaldorf** [comment]
I think a couple of syntax things are going wrong, which is why it doesn't work. In the first example, you're mixing up mixins and custom properties (see [this](https://www.polymer-project.org/1.0/docs/devguide/styling) for more info). Custom properties cascade down -- so if a `paper-input` defines a custom property `--foo`, and `paper-slider` uses a `paper-input`, then the `paper-slider` can explicitly just give a value to that property (and it will propagate to `paper-input`, where it's actually being used:

```
paper-slider {
  --foo: red;
}
```

The `--paper-input` mixin in paper slider is basically an extra bucket of properties you can apply to the specific `paper-input` that `paper-slider` uses, regardless of whatever custom properties the `paper-input` element defines:

```
paper-slider {
  --paper-input: {
    background: red;
    padding: 20px;
  }
}
```

Here's a jsbin that uses both of the mixin and the custom properties: http://jsbin.com/hiceqa/edit?html,output

Hope this helps!
