### ISSUE TITLE
Slider response to on-down which is not always desirable

### ISSUE THREAD

**Issue by andrey-git** [PolymerElements/paper-slider#178]
### Description
The `paper-slider` responds to `down` event on the container. This is not always desirable, as the user might be just accidentally putting the finger on the slider while trying to vertically scroll the page.

### Expected outcome
Vertical scroll starting at the slider shouldn't update the slider.
Respond to `tap` event only or make this configurable: `tap` or `down`

### Actual outcome
Vertical scroll starting at the slider changes slider value.

### Live Demo
https://www.webcomponents.org/element/PolymerElements/paper-slider/demo/demo/index.html

### Steps to reproduce

1. Put a `paper-slider` element in the page.
2. Open the page in a web browser.
3. Put finger/mouse on the slider and try to scroll down.

### Browsers Affected

All

**Comment by NovapaX** [comment]
This is simply fixed by changing
https://github.com/PolymerElements/paper-slider/blob/75c87eb82de3cae133ecaa61186b9d73a43c533d/paper-slider.html#L347
to `on-mousedown="_bardown"`
This is actually how it should behave from a UI/UX standpoint. (none of the sliders I've tried anywhere capture and act on touchstart on the bar on a touchscreen.)
