### ISSUE TITLE
Default dir='rtl' in Edge browser

### ISSUE THREAD

**Issue by kuenstl** [PolymerElements/paper-slider#204]
### Description
 The `paper-slider` works by default in 'rtl' direction in Edge browser. 

### Expected outcome

-  The `paper-slider` works same as in Chrome, Firefox and Edge browsers.
-  The `paper-slider` works by default in 'ltr' direction in Edge browser. 

### Actual outcome

 The `paper-slider` works by default in 'rtl' direction in Edge browser. 

### Live Demo
[webcomponents.org paper-slider demo page](https://www.webcomponents.org/element/PolymerElements/paper-slider)

### Steps to reproduce

1. Put a `paper-slider` element in the page.
2. Open the page in the Edge browser.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge

**Comment by keanulee** [comment]
Unclear what the issue is - the RTL demo works fine in Edge and other browsers (fill to the right of the knob, input to the left of the slider). Please provide a more detailed description if this is an issue.

![image](https://user-images.githubusercontent.com/1319720/32457835-447e2bf4-c2df-11e7-8bc3-02ad5fd42940.png)

**Comment by kuenstl** [comment]
Sorry, I forgot to mention the MS Edge version on which the issue appears.
On which version did you test the above pasted screenshot?
 
I tested the current [demo-page](https://www.webcomponents.org/element/PolymerElements/paper-slider/demo/demo/index.html) on browser-stack with MS Edge 41.16299.15.0 (MS EdgeHTML 16.16299):

![paper-slider-ms-edge](https://user-images.githubusercontent.com/16648213/32484992-0bbf89fc-c3a2-11e7-8f1f-8338d882de07.png)

**Comment by PatrickG** [comment]
I get the same results like @msteinberger.

Microsoft Edge 41.16299.15.0 (Microsoft EdgeHTML 16.16299)

**Comment by keanulee** [comment]
Issue verified - this is a result of:

* paper-slider used a `:host-context([dir="rtl"]) #sliderContainer` selector, which isn't actually supported with WC v1
  * https://github.com/PolymerElements/paper-slider/blob/de7bea58951782dc1448a06b3a82e49d4fc526da/paper-slider.html#L99
* This selector gets rewritten as `paper-slider-context([dir="rtl"]) #sliderContainer.paper-slider` by shady CSS (since `:host-context` is not a valid selector, but `:host` is)
* Edge 16 ignores the invalid parent selector (`paper-slider-context([dir="rtl"])` with the brackets is invalid) and applies the rules to `#sliderContainer.paper-slider`

Immediate fix is to use `:dir()` instead of `:host-context()` in paper-slider, but an Edge bug should be filed to ignore invalid selectors, and (maybe) shady CSS should gracefully remove invalid `:host-context()` rules.
