### ISSUE TITLE
API of mixins (maybe) not consistent

### ISSUE THREAD

**Issue by tswebcomponents** [PolymerElements/paper-slider#47]
Transforming the Polymer elements into typed classes and noticed that:
- paper-slider has behaviors:
  
  behaviors: [
    Polymer.IronRangeBehavior,
    Polymer.IronA11yKeysBehavior,
    Polymer.IronFormElementBehavior,
    Polymer.PaperInkyFocusBehavior
  ],
- IronFormElementBehavior has a property "value.type" of type String
- IronRangeBehavior has the same property a type Number

Although the JavaScript API is not strongly typed, but it is annotated with types is this a bug or is it possible that behaviors (sort of mixins/traits) can have different type definitions and the latest one overruled the latter or should this be fixed and is my transformation correct?

Thanks.

**Comment by blasten** [comment]
@tswebcomponents right. We had a long discussion about it: https://github.com/PolymerElements/paper-slider/pull/24

**Comment by tswebcomponents** [comment]
will check this. Thanks!

**Comment by tswebcomponents** [comment]
Long discussion I don't completely understand. conclusion is compile time the types do not have to be the same of behaviors if they can be converted runtime? This means the compiler will not succeed or am I missing something? (a commit or ...)

Thanks.

**Comment by blasten** [comment]
yes. we had to override the type of `value`. You can override properties depending on the order of the behaviors in the `behavior` array.

**Comment by notwaldorf** [comment]
@tswebcomponents the tl; dr is that `value` is needed so that `paper-slider` can be added to a form. Normally this property comes from `IronFormElementBehavior`, and it's type is `String`. However, in the specific case of `paper-slider`, its value is `Number`, not `String`, and Bad Things™ would happen if you assumed it was a Number and it wasn't (for example, math would be wonky). Also, the JS compiler hates it.

The only two options were: a) copy paste everything from `IronFormElementBehavior`, and type `value` as Number (bad because in the future we're going to forget `paper-slider` went rogue) or b) use `IronFormElementBehavior`, but make sure to override its value and set it to the right type.

Ideally, `value` would be abstract and every element implementing `IronFormElementBehavior` would  specify its type, but that is not a world we live in at the moment :)
