### ISSUE TITLE
[feature request] make it possible to have a min-value and max-value

### ISSUE THREAD

**Issue by Evertt** [PolymerElements/paper-slider#8]
Title says it all. [Here's an example of what I mean.](http://jqueryui.com/slider/#range)

**Comment by NicolasRannou** [comment]
Not sure it will be ever supported since it is not an "official" paper element.

However, it is fairly straight forward to extend this paper-slider to get a range slider.
I've been playing a bit with it a while back and you can find an example of implementation there:
http://nicolasrannou.github.io/paper-rangeslider/paper-rangeslider/demo/

Now that polymer 1.0 has shipped I'll fix the remaining bugs on my demo and provide a proper polymer-like solution, as close as the paper-slider a possible to keep both in sync as much as possible.

**Comment by Evertt** [comment]
Awesome man, that's great. I feel grateful that you already made one. I look forward to your 1.0 version and from that point on, if you want to stop supporting it, I'll fork it and take over. :-)

**Comment by blasten** [comment]
As @Evertt pointed out, the material design spec for sliders doesn't have a concept of `min-value`. https://www.google.com/design/spec/components/sliders.html#sliders-discrete-slider  

However, `iron-range-behavior` does give you a starting point for anything that has a range, so you can extend from that behavior. 
https://github.com/PolymerElements/iron-range-behavior

Thanks @Evertt for the example.
